name:                tic-tac-toe
version:             0.1.0.0
github:              "plumenator/tic-tac-toe"
license:             BSD3
author:              "Karthik Ravikanti"
maintainer:          "karthik.ravikanti@gmail.com"
copyright:           "2022 Karthik Ravikanti"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/plumenator/tic-tac-toe#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - QuickCheck

executables:
  tic-tac-toe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tic-tac-toe
    - either

tests:
  tic-tac-toe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tic-tac-toe
    - hspec
    - QuickCheck
